### ISSUE TITLE
User Admin: Add comments field to user details page 

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/userdetails#64] opened 2019-02-21 00:59 UTC
**Background.**

User accounts are usually deactivated on user account owner request or a request from a product owner.

While this can be easily achieved in userdetails, currently there is no way to capture a reason so in the future if an admin visits the account details he/she knows why the account has been disabled. 

The above becomes critical in cases where an account has been disabled because the user has breached the terms of use. There is no way for an admin to know that account should remain disabled other than by relying in other systems (Freshdesk) or been communicated by another colleague.

**Requirements**

- Add a comments field (Text Area) to Edit User screen where notes can be added for that particular user.

- The Show User view must display the new comments field.

- The comments field it's a field that will be available only to administrators of userdetails and this field should be hidden from any self serve pages.

**Comment by matthewandrews** [comment] 2019-02-21 01:08
@javier-molina  - this looks like a duplicate of #61 ...

**Comment by javier-molina** [comment] 2019-02-21 03:38
Thanks @matthewandrews this is a follow up task from Freshdesk ticket 29537. I should check more in detail the backlog rather than just skimming through creation date.

@nickdos fyi.

**Closed** 2019-02-21 03:39 UTC
